apiVersion: v1
kind: Service
metadata:
  name: {{ include "airmon-graphql.fullname" . }}
  labels:
{{ include "airmon-graphql.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http-80
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: http-443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "airmon-graphql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
