{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "airmon-graphql.serviceAccountName" . }}
  labels:
{{ include "airmon-graphql.labels" . | indent 4 }}
{{- end -}}
